//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColleageInnerTraining.Web.AuthServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemUserBase", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ColleageInnerTraining.Web.AuthServiceProxy.SystemUser))]
    public partial class SystemUserBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SysNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        private ColleageInnerTraining.Web.AuthServiceProxy.UserStatus StatusField;
        
        private int InUserField;
        
        private System.DateTime InDateField;
        
        private int EditUserField;
        
        private System.DateTime EditDateField;
        
        private int DepartmentIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserDepartmentNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserDepartmentDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordSaltField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SysNO {
            get {
                return this.SysNOField;
            }
            set {
                if ((this.SysNOField.Equals(value) != true)) {
                    this.SysNOField = value;
                    this.RaisePropertyChanged("SysNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string LoginName {
            get {
                return this.LoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginNameField, value) != true)) {
                    this.LoginNameField = value;
                    this.RaisePropertyChanged("LoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public ColleageInnerTraining.Web.AuthServiceProxy.UserStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int InUser {
            get {
                return this.InUserField;
            }
            set {
                if ((this.InUserField.Equals(value) != true)) {
                    this.InUserField = value;
                    this.RaisePropertyChanged("InUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.DateTime InDate {
            get {
                return this.InDateField;
            }
            set {
                if ((this.InDateField.Equals(value) != true)) {
                    this.InDateField = value;
                    this.RaisePropertyChanged("InDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public int EditUser {
            get {
                return this.EditUserField;
            }
            set {
                if ((this.EditUserField.Equals(value) != true)) {
                    this.EditUserField = value;
                    this.RaisePropertyChanged("EditUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime EditDate {
            get {
                return this.EditDateField;
            }
            set {
                if ((this.EditDateField.Equals(value) != true)) {
                    this.EditDateField = value;
                    this.RaisePropertyChanged("EditDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public int DepartmentID {
            get {
                return this.DepartmentIDField;
            }
            set {
                if ((this.DepartmentIDField.Equals(value) != true)) {
                    this.DepartmentIDField = value;
                    this.RaisePropertyChanged("DepartmentID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string UserDepartmentName {
            get {
                return this.UserDepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDepartmentNameField, value) != true)) {
                    this.UserDepartmentNameField = value;
                    this.RaisePropertyChanged("UserDepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string UserDepartmentDescription {
            get {
                return this.UserDepartmentDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.UserDepartmentDescriptionField, value) != true)) {
                    this.UserDepartmentDescriptionField = value;
                    this.RaisePropertyChanged("UserDepartmentDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string PasswordSalt {
            get {
                return this.PasswordSaltField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordSaltField, value) != true)) {
                    this.PasswordSaltField = value;
                    this.RaisePropertyChanged("PasswordSalt");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemUser", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SystemUser : ColleageInnerTraining.Web.AuthServiceProxy.SystemUserBase {
        
        private int CompanySysNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CompanySysNO {
            get {
                return this.CompanySysNOField;
            }
            set {
                if ((this.CompanySysNOField.Equals(value) != true)) {
                    this.CompanySysNOField = value;
                    this.RaisePropertyChanged("CompanySysNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CompanyCode {
            get {
                return this.CompanyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyCodeField, value) != true)) {
                    this.CompanyCodeField = value;
                    this.RaisePropertyChanged("CompanyCode");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserStatus", Namespace="urn:Gznb.authcenter")]
    public enum UserStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disabled = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enabled = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemRole", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SystemRole : ColleageInnerTraining.Web.AuthServiceProxy.SystemRoleBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ColleageInnerTraining.Web.AuthServiceProxy.SystemFunction[] FunctionListField;
        
        private bool UserHadField;
        
        private int CompanySysNOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ApplicationName {
            get {
                return this.ApplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNameField, value) != true)) {
                    this.ApplicationNameField = value;
                    this.RaisePropertyChanged("ApplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public ColleageInnerTraining.Web.AuthServiceProxy.SystemFunction[] FunctionList {
            get {
                return this.FunctionListField;
            }
            set {
                if ((object.ReferenceEquals(this.FunctionListField, value) != true)) {
                    this.FunctionListField = value;
                    this.RaisePropertyChanged("FunctionList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool UserHad {
            get {
                return this.UserHadField;
            }
            set {
                if ((this.UserHadField.Equals(value) != true)) {
                    this.UserHadField = value;
                    this.RaisePropertyChanged("UserHad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int CompanySysNO {
            get {
                return this.CompanySysNOField;
            }
            set {
                if ((this.CompanySysNOField.Equals(value) != true)) {
                    this.CompanySysNOField = value;
                    this.RaisePropertyChanged("CompanySysNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemRoleBase", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ColleageInnerTraining.Web.AuthServiceProxy.SystemRole))]
    public partial class SystemRoleBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SysNOField;
        
        private System.Guid ApplicationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomConditionField;
        
        private System.Nullable<int> ParentRoleSysNOField;
        
        private ColleageInnerTraining.Web.AuthServiceProxy.RoleStatus StatusField;
        
        private int InUserField;
        
        private System.DateTime InDateField;
        
        private int EditUserField;
        
        private System.DateTime EditDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SysNO {
            get {
                return this.SysNOField;
            }
            set {
                if ((this.SysNOField.Equals(value) != true)) {
                    this.SysNOField = value;
                    this.RaisePropertyChanged("SysNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Guid ApplicationID {
            get {
                return this.ApplicationIDField;
            }
            set {
                if ((this.ApplicationIDField.Equals(value) != true)) {
                    this.ApplicationIDField = value;
                    this.RaisePropertyChanged("ApplicationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CustomCondition {
            get {
                return this.CustomConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomConditionField, value) != true)) {
                    this.CustomConditionField = value;
                    this.RaisePropertyChanged("CustomCondition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> ParentRoleSysNO {
            get {
                return this.ParentRoleSysNOField;
            }
            set {
                if ((this.ParentRoleSysNOField.Equals(value) != true)) {
                    this.ParentRoleSysNOField = value;
                    this.RaisePropertyChanged("ParentRoleSysNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public ColleageInnerTraining.Web.AuthServiceProxy.RoleStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int InUser {
            get {
                return this.InUserField;
            }
            set {
                if ((this.InUserField.Equals(value) != true)) {
                    this.InUserField = value;
                    this.RaisePropertyChanged("InUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime InDate {
            get {
                return this.InDateField;
            }
            set {
                if ((this.InDateField.Equals(value) != true)) {
                    this.InDateField = value;
                    this.RaisePropertyChanged("InDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int EditUser {
            get {
                return this.EditUserField;
            }
            set {
                if ((this.EditUserField.Equals(value) != true)) {
                    this.EditUserField = value;
                    this.RaisePropertyChanged("EditUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime EditDate {
            get {
                return this.EditDateField;
            }
            set {
                if ((this.EditDateField.Equals(value) != true)) {
                    this.EditDateField = value;
                    this.RaisePropertyChanged("EditDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleStatus", Namespace="http://tempuri.org/")]
    public enum RoleStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disabled = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enabled = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemFunction", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SystemFunction : ColleageInnerTraining.Web.AuthServiceProxy.SystemFunctionBase {
        
        private bool UserHadField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool UserHad {
            get {
                return this.UserHadField;
            }
            set {
                if ((this.UserHadField.Equals(value) != true)) {
                    this.UserHadField = value;
                    this.RaisePropertyChanged("UserHad");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemFunctionBase", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ColleageInnerTraining.Web.AuthServiceProxy.SystemFunction))]
    public partial class SystemFunctionBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int SysNOField;
        
        private System.Guid ApplicationIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthKeyField;
        
        private ColleageInnerTraining.Web.AuthServiceProxy.FunctionType TypeField;
        
        private ColleageInnerTraining.Web.AuthServiceProxy.FunctionStatus StatusField;
        
        private int InUserField;
        
        private System.DateTime InDateField;
        
        private int EditUserField;
        
        private System.DateTime EditDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int SysNO {
            get {
                return this.SysNOField;
            }
            set {
                if ((this.SysNOField.Equals(value) != true)) {
                    this.SysNOField = value;
                    this.RaisePropertyChanged("SysNO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.Guid ApplicationID {
            get {
                return this.ApplicationIDField;
            }
            set {
                if ((this.ApplicationIDField.Equals(value) != true)) {
                    this.ApplicationIDField = value;
                    this.RaisePropertyChanged("ApplicationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AuthKey {
            get {
                return this.AuthKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthKeyField, value) != true)) {
                    this.AuthKeyField = value;
                    this.RaisePropertyChanged("AuthKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public ColleageInnerTraining.Web.AuthServiceProxy.FunctionType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public ColleageInnerTraining.Web.AuthServiceProxy.FunctionStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int InUser {
            get {
                return this.InUserField;
            }
            set {
                if ((this.InUserField.Equals(value) != true)) {
                    this.InUserField = value;
                    this.RaisePropertyChanged("InUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime InDate {
            get {
                return this.InDateField;
            }
            set {
                if ((this.InDateField.Equals(value) != true)) {
                    this.InDateField = value;
                    this.RaisePropertyChanged("InDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int EditUser {
            get {
                return this.EditUserField;
            }
            set {
                if ((this.EditUserField.Equals(value) != true)) {
                    this.EditUserField = value;
                    this.RaisePropertyChanged("EditUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.DateTime EditDate {
            get {
                return this.EditDateField;
            }
            set {
                if ((this.EditDateField.Equals(value) != true)) {
                    this.EditDateField = value;
                    this.RaisePropertyChanged("EditDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FunctionType", Namespace="http://tempuri.org/")]
    public enum FunctionType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Page = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Button = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FunctionStatus", Namespace="http://tempuri.org/")]
    public enum FunctionStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Disabled = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Enabled = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthServiceProxy.AuthServiceSoap")]
    public interface AuthServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        ColleageInnerTraining.Web.AuthServiceProxy.LoginResponse Login(ColleageInnerTraining.Web.AuthServiceProxy.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.LoginResponse> LoginAsync(ColleageInnerTraining.Web.AuthServiceProxy.LoginRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginAuth", ReplyAction="*")]
        ColleageInnerTraining.Web.AuthServiceProxy.LoginAuthResponse LoginAuth(ColleageInnerTraining.Web.AuthServiceProxy.LoginAuthRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginAuth", ReplyAction="*")]
        System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.LoginAuthResponse> LoginAuthAsync(ColleageInnerTraining.Web.AuthServiceProxy.LoginAuthRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrustedLogin", ReplyAction="*")]
        ColleageInnerTraining.Web.AuthServiceProxy.TrustedLoginResponse TrustedLogin(ColleageInnerTraining.Web.AuthServiceProxy.TrustedLoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TrustedLogin", ReplyAction="*")]
        System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.TrustedLoginResponse> TrustedLoginAsync(ColleageInnerTraining.Web.AuthServiceProxy.TrustedLoginRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        ColleageInnerTraining.Web.AuthServiceProxy.ChangePasswordResponse ChangePassword(ColleageInnerTraining.Web.AuthServiceProxy.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.ChangePasswordResponse> ChangePasswordAsync(ColleageInnerTraining.Web.AuthServiceProxy.ChangePasswordRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 applicationID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserFunction", ReplyAction="*")]
        ColleageInnerTraining.Web.AuthServiceProxy.GetUserFunctionResponse GetUserFunction(ColleageInnerTraining.Web.AuthServiceProxy.GetUserFunctionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserFunction", ReplyAction="*")]
        System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.GetUserFunctionResponse> GetUserFunctionAsync(ColleageInnerTraining.Web.AuthServiceProxy.GetUserFunctionRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 applicationID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserAuthKey", ReplyAction="*")]
        ColleageInnerTraining.Web.AuthServiceProxy.GetUserAuthKeyResponse GetUserAuthKey(ColleageInnerTraining.Web.AuthServiceProxy.GetUserAuthKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserAuthKey", ReplyAction="*")]
        System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.GetUserAuthKeyResponse> GetUserAuthKeyAsync(ColleageInnerTraining.Web.AuthServiceProxy.GetUserAuthKeyRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 applicationID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserFunction", ReplyAction="*")]
        ColleageInnerTraining.Web.AuthServiceProxy.CheckUserFunctionResponse CheckUserFunction(ColleageInnerTraining.Web.AuthServiceProxy.CheckUserFunctionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CheckUserFunction", ReplyAction="*")]
        System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.CheckUserFunctionResponse> CheckUserFunctionAsync(ColleageInnerTraining.Web.AuthServiceProxy.CheckUserFunctionRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 applicationID 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSystemUserByApplicationID", ReplyAction="*")]
        ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByApplicationIDResponse GetSystemUserByApplicationID(ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByApplicationIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSystemUserByApplicationID", ReplyAction="*")]
        System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByApplicationIDResponse> GetSystemUserByApplicationIDAsync(ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByApplicationIDRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetSystemUserBySysNoResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSystemUserBySysNo", ReplyAction="*")]
        ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserBySysNoResponse GetSystemUserBySysNo(ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserBySysNoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSystemUserBySysNo", ReplyAction="*")]
        System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserBySysNoResponse> GetSystemUserBySysNoAsync(ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserBySysNoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 loginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSystemUserByLoginName", ReplyAction="*")]
        ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByLoginNameResponse GetSystemUserByLoginName(ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByLoginNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSystemUserByLoginName", ReplyAction="*")]
        System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByLoginNameResponse> GetSystemUserByLoginNameAsync(ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByLoginNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(ColleageInnerTraining.Web.AuthServiceProxy.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string loginName, string password) {
            this.loginName = loginName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(ColleageInnerTraining.Web.AuthServiceProxy.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.SystemUser LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(ColleageInnerTraining.Web.AuthServiceProxy.SystemUser LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginAuthRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginAuth", Namespace="http://tempuri.org/", Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.LoginAuthRequestBody Body;
        
        public LoginAuthRequest() {
        }
        
        public LoginAuthRequest(ColleageInnerTraining.Web.AuthServiceProxy.LoginAuthRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginAuthRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginAuthRequestBody() {
        }
        
        public LoginAuthRequestBody(string loginName, string password) {
            this.loginName = loginName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginAuthResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginAuthResponse", Namespace="http://tempuri.org/", Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.LoginAuthResponseBody Body;
        
        public LoginAuthResponse() {
        }
        
        public LoginAuthResponse(ColleageInnerTraining.Web.AuthServiceProxy.LoginAuthResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginAuthResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.SystemUser LoginAuthResult;
        
        public LoginAuthResponseBody() {
        }
        
        public LoginAuthResponseBody(ColleageInnerTraining.Web.AuthServiceProxy.SystemUser LoginAuthResult) {
            this.LoginAuthResult = LoginAuthResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrustedLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrustedLogin", Namespace="http://tempuri.org/", Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.TrustedLoginRequestBody Body;
        
        public TrustedLoginRequest() {
        }
        
        public TrustedLoginRequest(ColleageInnerTraining.Web.AuthServiceProxy.TrustedLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TrustedLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        public TrustedLoginRequestBody() {
        }
        
        public TrustedLoginRequestBody(string loginName) {
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TrustedLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TrustedLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.TrustedLoginResponseBody Body;
        
        public TrustedLoginResponse() {
        }
        
        public TrustedLoginResponse(ColleageInnerTraining.Web.AuthServiceProxy.TrustedLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class TrustedLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.SystemUser TrustedLoginResult;
        
        public TrustedLoginResponseBody() {
        }
        
        public TrustedLoginResponseBody(ColleageInnerTraining.Web.AuthServiceProxy.SystemUser TrustedLoginResult) {
            this.TrustedLoginResult = TrustedLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePassword", Namespace="http://tempuri.org/", Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.ChangePasswordRequestBody Body;
        
        public ChangePasswordRequest() {
        }
        
        public ChangePasswordRequest(ColleageInnerTraining.Web.AuthServiceProxy.ChangePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oldPassword;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newPassword;
        
        public ChangePasswordRequestBody() {
        }
        
        public ChangePasswordRequestBody(string loginName, string oldPassword, string newPassword) {
            this.loginName = loginName;
            this.oldPassword = oldPassword;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.ChangePasswordResponseBody Body;
        
        public ChangePasswordResponse() {
        }
        
        public ChangePasswordResponse(ColleageInnerTraining.Web.AuthServiceProxy.ChangePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.SystemUser ChangePasswordResult;
        
        public ChangePasswordResponseBody() {
        }
        
        public ChangePasswordResponseBody(ColleageInnerTraining.Web.AuthServiceProxy.SystemUser ChangePasswordResult) {
            this.ChangePasswordResult = ChangePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserFunctionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserFunction", Namespace="http://tempuri.org/", Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.GetUserFunctionRequestBody Body;
        
        public GetUserFunctionRequest() {
        }
        
        public GetUserFunctionRequest(ColleageInnerTraining.Web.AuthServiceProxy.GetUserFunctionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserFunctionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string applicationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string loginName;
        
        public GetUserFunctionRequestBody() {
        }
        
        public GetUserFunctionRequestBody(string applicationID, string loginName) {
            this.applicationID = applicationID;
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserFunctionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserFunctionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.GetUserFunctionResponseBody Body;
        
        public GetUserFunctionResponse() {
        }
        
        public GetUserFunctionResponse(ColleageInnerTraining.Web.AuthServiceProxy.GetUserFunctionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserFunctionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.SystemRole[] GetUserFunctionResult;
        
        public GetUserFunctionResponseBody() {
        }
        
        public GetUserFunctionResponseBody(ColleageInnerTraining.Web.AuthServiceProxy.SystemRole[] GetUserFunctionResult) {
            this.GetUserFunctionResult = GetUserFunctionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserAuthKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserAuthKey", Namespace="http://tempuri.org/", Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.GetUserAuthKeyRequestBody Body;
        
        public GetUserAuthKeyRequest() {
        }
        
        public GetUserAuthKeyRequest(ColleageInnerTraining.Web.AuthServiceProxy.GetUserAuthKeyRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserAuthKeyRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string applicationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string loginName;
        
        public GetUserAuthKeyRequestBody() {
        }
        
        public GetUserAuthKeyRequestBody(string applicationID, string loginName) {
            this.applicationID = applicationID;
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserAuthKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserAuthKeyResponse", Namespace="http://tempuri.org/", Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.GetUserAuthKeyResponseBody Body;
        
        public GetUserAuthKeyResponse() {
        }
        
        public GetUserAuthKeyResponse(ColleageInnerTraining.Web.AuthServiceProxy.GetUserAuthKeyResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserAuthKeyResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.ArrayOfString GetUserAuthKeyResult;
        
        public GetUserAuthKeyResponseBody() {
        }
        
        public GetUserAuthKeyResponseBody(ColleageInnerTraining.Web.AuthServiceProxy.ArrayOfString GetUserAuthKeyResult) {
            this.GetUserAuthKeyResult = GetUserAuthKeyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserFunctionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserFunction", Namespace="http://tempuri.org/", Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.CheckUserFunctionRequestBody Body;
        
        public CheckUserFunctionRequest() {
        }
        
        public CheckUserFunctionRequest(ColleageInnerTraining.Web.AuthServiceProxy.CheckUserFunctionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserFunctionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string applicationID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string loginName;
        
        public CheckUserFunctionRequestBody() {
        }
        
        public CheckUserFunctionRequestBody(string applicationID, string authKey, string loginName) {
            this.applicationID = applicationID;
            this.authKey = authKey;
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckUserFunctionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckUserFunctionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.CheckUserFunctionResponseBody Body;
        
        public CheckUserFunctionResponse() {
        }
        
        public CheckUserFunctionResponse(ColleageInnerTraining.Web.AuthServiceProxy.CheckUserFunctionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CheckUserFunctionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CheckUserFunctionResult;
        
        public CheckUserFunctionResponseBody() {
        }
        
        public CheckUserFunctionResponseBody(bool CheckUserFunctionResult) {
            this.CheckUserFunctionResult = CheckUserFunctionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemUserByApplicationIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSystemUserByApplicationID", Namespace="http://tempuri.org/", Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByApplicationIDRequestBody Body;
        
        public GetSystemUserByApplicationIDRequest() {
        }
        
        public GetSystemUserByApplicationIDRequest(ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByApplicationIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSystemUserByApplicationIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string applicationID;
        
        public GetSystemUserByApplicationIDRequestBody() {
        }
        
        public GetSystemUserByApplicationIDRequestBody(string applicationID) {
            this.applicationID = applicationID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemUserByApplicationIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSystemUserByApplicationIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByApplicationIDResponseBody Body;
        
        public GetSystemUserByApplicationIDResponse() {
        }
        
        public GetSystemUserByApplicationIDResponse(ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByApplicationIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSystemUserByApplicationIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.SystemUser[] GetSystemUserByApplicationIDResult;
        
        public GetSystemUserByApplicationIDResponseBody() {
        }
        
        public GetSystemUserByApplicationIDResponseBody(ColleageInnerTraining.Web.AuthServiceProxy.SystemUser[] GetSystemUserByApplicationIDResult) {
            this.GetSystemUserByApplicationIDResult = GetSystemUserByApplicationIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemUserBySysNoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSystemUserBySysNo", Namespace="http://tempuri.org/", Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserBySysNoRequestBody Body;
        
        public GetSystemUserBySysNoRequest() {
        }
        
        public GetSystemUserBySysNoRequest(ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserBySysNoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSystemUserBySysNoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sysNo;
        
        public GetSystemUserBySysNoRequestBody() {
        }
        
        public GetSystemUserBySysNoRequestBody(int sysNo) {
            this.sysNo = sysNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemUserBySysNoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSystemUserBySysNoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserBySysNoResponseBody Body;
        
        public GetSystemUserBySysNoResponse() {
        }
        
        public GetSystemUserBySysNoResponse(ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserBySysNoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSystemUserBySysNoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.SystemUser GetSystemUserBySysNoResult;
        
        public GetSystemUserBySysNoResponseBody() {
        }
        
        public GetSystemUserBySysNoResponseBody(ColleageInnerTraining.Web.AuthServiceProxy.SystemUser GetSystemUserBySysNoResult) {
            this.GetSystemUserBySysNoResult = GetSystemUserBySysNoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemUserByLoginNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSystemUserByLoginName", Namespace="http://tempuri.org/", Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByLoginNameRequestBody Body;
        
        public GetSystemUserByLoginNameRequest() {
        }
        
        public GetSystemUserByLoginNameRequest(ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByLoginNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSystemUserByLoginNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginName;
        
        public GetSystemUserByLoginNameRequestBody() {
        }
        
        public GetSystemUserByLoginNameRequestBody(string loginName) {
            this.loginName = loginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSystemUserByLoginNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSystemUserByLoginNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByLoginNameResponseBody Body;
        
        public GetSystemUserByLoginNameResponse() {
        }
        
        public GetSystemUserByLoginNameResponse(ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByLoginNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSystemUserByLoginNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ColleageInnerTraining.Web.AuthServiceProxy.SystemUser GetSystemUserByLoginNameResult;
        
        public GetSystemUserByLoginNameResponseBody() {
        }
        
        public GetSystemUserByLoginNameResponseBody(ColleageInnerTraining.Web.AuthServiceProxy.SystemUser GetSystemUserByLoginNameResult) {
            this.GetSystemUserByLoginNameResult = GetSystemUserByLoginNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthServiceSoapChannel : ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthServiceSoapClient : System.ServiceModel.ClientBase<ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap>, ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap {
        
        public AuthServiceSoapClient() {
        }
        
        public AuthServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ColleageInnerTraining.Web.AuthServiceProxy.LoginResponse ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap.Login(ColleageInnerTraining.Web.AuthServiceProxy.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public ColleageInnerTraining.Web.AuthServiceProxy.SystemUser Login(string loginName, string password) {
            ColleageInnerTraining.Web.AuthServiceProxy.LoginRequest inValue = new ColleageInnerTraining.Web.AuthServiceProxy.LoginRequest();
            inValue.Body = new ColleageInnerTraining.Web.AuthServiceProxy.LoginRequestBody();
            inValue.Body.loginName = loginName;
            inValue.Body.password = password;
            ColleageInnerTraining.Web.AuthServiceProxy.LoginResponse retVal = ((ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.LoginResponse> ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap.LoginAsync(ColleageInnerTraining.Web.AuthServiceProxy.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.LoginResponse> LoginAsync(string loginName, string password) {
            ColleageInnerTraining.Web.AuthServiceProxy.LoginRequest inValue = new ColleageInnerTraining.Web.AuthServiceProxy.LoginRequest();
            inValue.Body = new ColleageInnerTraining.Web.AuthServiceProxy.LoginRequestBody();
            inValue.Body.loginName = loginName;
            inValue.Body.password = password;
            return ((ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ColleageInnerTraining.Web.AuthServiceProxy.LoginAuthResponse ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap.LoginAuth(ColleageInnerTraining.Web.AuthServiceProxy.LoginAuthRequest request) {
            return base.Channel.LoginAuth(request);
        }
        
        public ColleageInnerTraining.Web.AuthServiceProxy.SystemUser LoginAuth(string loginName, string password) {
            ColleageInnerTraining.Web.AuthServiceProxy.LoginAuthRequest inValue = new ColleageInnerTraining.Web.AuthServiceProxy.LoginAuthRequest();
            inValue.Body = new ColleageInnerTraining.Web.AuthServiceProxy.LoginAuthRequestBody();
            inValue.Body.loginName = loginName;
            inValue.Body.password = password;
            ColleageInnerTraining.Web.AuthServiceProxy.LoginAuthResponse retVal = ((ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap)(this)).LoginAuth(inValue);
            return retVal.Body.LoginAuthResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.LoginAuthResponse> ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap.LoginAuthAsync(ColleageInnerTraining.Web.AuthServiceProxy.LoginAuthRequest request) {
            return base.Channel.LoginAuthAsync(request);
        }
        
        public System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.LoginAuthResponse> LoginAuthAsync(string loginName, string password) {
            ColleageInnerTraining.Web.AuthServiceProxy.LoginAuthRequest inValue = new ColleageInnerTraining.Web.AuthServiceProxy.LoginAuthRequest();
            inValue.Body = new ColleageInnerTraining.Web.AuthServiceProxy.LoginAuthRequestBody();
            inValue.Body.loginName = loginName;
            inValue.Body.password = password;
            return ((ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap)(this)).LoginAuthAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ColleageInnerTraining.Web.AuthServiceProxy.TrustedLoginResponse ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap.TrustedLogin(ColleageInnerTraining.Web.AuthServiceProxy.TrustedLoginRequest request) {
            return base.Channel.TrustedLogin(request);
        }
        
        public ColleageInnerTraining.Web.AuthServiceProxy.SystemUser TrustedLogin(string loginName) {
            ColleageInnerTraining.Web.AuthServiceProxy.TrustedLoginRequest inValue = new ColleageInnerTraining.Web.AuthServiceProxy.TrustedLoginRequest();
            inValue.Body = new ColleageInnerTraining.Web.AuthServiceProxy.TrustedLoginRequestBody();
            inValue.Body.loginName = loginName;
            ColleageInnerTraining.Web.AuthServiceProxy.TrustedLoginResponse retVal = ((ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap)(this)).TrustedLogin(inValue);
            return retVal.Body.TrustedLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.TrustedLoginResponse> ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap.TrustedLoginAsync(ColleageInnerTraining.Web.AuthServiceProxy.TrustedLoginRequest request) {
            return base.Channel.TrustedLoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.TrustedLoginResponse> TrustedLoginAsync(string loginName) {
            ColleageInnerTraining.Web.AuthServiceProxy.TrustedLoginRequest inValue = new ColleageInnerTraining.Web.AuthServiceProxy.TrustedLoginRequest();
            inValue.Body = new ColleageInnerTraining.Web.AuthServiceProxy.TrustedLoginRequestBody();
            inValue.Body.loginName = loginName;
            return ((ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap)(this)).TrustedLoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ColleageInnerTraining.Web.AuthServiceProxy.ChangePasswordResponse ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap.ChangePassword(ColleageInnerTraining.Web.AuthServiceProxy.ChangePasswordRequest request) {
            return base.Channel.ChangePassword(request);
        }
        
        public ColleageInnerTraining.Web.AuthServiceProxy.SystemUser ChangePassword(string loginName, string oldPassword, string newPassword) {
            ColleageInnerTraining.Web.AuthServiceProxy.ChangePasswordRequest inValue = new ColleageInnerTraining.Web.AuthServiceProxy.ChangePasswordRequest();
            inValue.Body = new ColleageInnerTraining.Web.AuthServiceProxy.ChangePasswordRequestBody();
            inValue.Body.loginName = loginName;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            ColleageInnerTraining.Web.AuthServiceProxy.ChangePasswordResponse retVal = ((ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap)(this)).ChangePassword(inValue);
            return retVal.Body.ChangePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.ChangePasswordResponse> ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap.ChangePasswordAsync(ColleageInnerTraining.Web.AuthServiceProxy.ChangePasswordRequest request) {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.ChangePasswordResponse> ChangePasswordAsync(string loginName, string oldPassword, string newPassword) {
            ColleageInnerTraining.Web.AuthServiceProxy.ChangePasswordRequest inValue = new ColleageInnerTraining.Web.AuthServiceProxy.ChangePasswordRequest();
            inValue.Body = new ColleageInnerTraining.Web.AuthServiceProxy.ChangePasswordRequestBody();
            inValue.Body.loginName = loginName;
            inValue.Body.oldPassword = oldPassword;
            inValue.Body.newPassword = newPassword;
            return ((ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap)(this)).ChangePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ColleageInnerTraining.Web.AuthServiceProxy.GetUserFunctionResponse ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap.GetUserFunction(ColleageInnerTraining.Web.AuthServiceProxy.GetUserFunctionRequest request) {
            return base.Channel.GetUserFunction(request);
        }
        
        public ColleageInnerTraining.Web.AuthServiceProxy.SystemRole[] GetUserFunction(string applicationID, string loginName) {
            ColleageInnerTraining.Web.AuthServiceProxy.GetUserFunctionRequest inValue = new ColleageInnerTraining.Web.AuthServiceProxy.GetUserFunctionRequest();
            inValue.Body = new ColleageInnerTraining.Web.AuthServiceProxy.GetUserFunctionRequestBody();
            inValue.Body.applicationID = applicationID;
            inValue.Body.loginName = loginName;
            ColleageInnerTraining.Web.AuthServiceProxy.GetUserFunctionResponse retVal = ((ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap)(this)).GetUserFunction(inValue);
            return retVal.Body.GetUserFunctionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.GetUserFunctionResponse> ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap.GetUserFunctionAsync(ColleageInnerTraining.Web.AuthServiceProxy.GetUserFunctionRequest request) {
            return base.Channel.GetUserFunctionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.GetUserFunctionResponse> GetUserFunctionAsync(string applicationID, string loginName) {
            ColleageInnerTraining.Web.AuthServiceProxy.GetUserFunctionRequest inValue = new ColleageInnerTraining.Web.AuthServiceProxy.GetUserFunctionRequest();
            inValue.Body = new ColleageInnerTraining.Web.AuthServiceProxy.GetUserFunctionRequestBody();
            inValue.Body.applicationID = applicationID;
            inValue.Body.loginName = loginName;
            return ((ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap)(this)).GetUserFunctionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ColleageInnerTraining.Web.AuthServiceProxy.GetUserAuthKeyResponse ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap.GetUserAuthKey(ColleageInnerTraining.Web.AuthServiceProxy.GetUserAuthKeyRequest request) {
            return base.Channel.GetUserAuthKey(request);
        }
        
        public ColleageInnerTraining.Web.AuthServiceProxy.ArrayOfString GetUserAuthKey(string applicationID, string loginName) {
            ColleageInnerTraining.Web.AuthServiceProxy.GetUserAuthKeyRequest inValue = new ColleageInnerTraining.Web.AuthServiceProxy.GetUserAuthKeyRequest();
            inValue.Body = new ColleageInnerTraining.Web.AuthServiceProxy.GetUserAuthKeyRequestBody();
            inValue.Body.applicationID = applicationID;
            inValue.Body.loginName = loginName;
            ColleageInnerTraining.Web.AuthServiceProxy.GetUserAuthKeyResponse retVal = ((ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap)(this)).GetUserAuthKey(inValue);
            return retVal.Body.GetUserAuthKeyResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.GetUserAuthKeyResponse> ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap.GetUserAuthKeyAsync(ColleageInnerTraining.Web.AuthServiceProxy.GetUserAuthKeyRequest request) {
            return base.Channel.GetUserAuthKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.GetUserAuthKeyResponse> GetUserAuthKeyAsync(string applicationID, string loginName) {
            ColleageInnerTraining.Web.AuthServiceProxy.GetUserAuthKeyRequest inValue = new ColleageInnerTraining.Web.AuthServiceProxy.GetUserAuthKeyRequest();
            inValue.Body = new ColleageInnerTraining.Web.AuthServiceProxy.GetUserAuthKeyRequestBody();
            inValue.Body.applicationID = applicationID;
            inValue.Body.loginName = loginName;
            return ((ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap)(this)).GetUserAuthKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ColleageInnerTraining.Web.AuthServiceProxy.CheckUserFunctionResponse ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap.CheckUserFunction(ColleageInnerTraining.Web.AuthServiceProxy.CheckUserFunctionRequest request) {
            return base.Channel.CheckUserFunction(request);
        }
        
        public bool CheckUserFunction(string applicationID, string authKey, string loginName) {
            ColleageInnerTraining.Web.AuthServiceProxy.CheckUserFunctionRequest inValue = new ColleageInnerTraining.Web.AuthServiceProxy.CheckUserFunctionRequest();
            inValue.Body = new ColleageInnerTraining.Web.AuthServiceProxy.CheckUserFunctionRequestBody();
            inValue.Body.applicationID = applicationID;
            inValue.Body.authKey = authKey;
            inValue.Body.loginName = loginName;
            ColleageInnerTraining.Web.AuthServiceProxy.CheckUserFunctionResponse retVal = ((ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap)(this)).CheckUserFunction(inValue);
            return retVal.Body.CheckUserFunctionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.CheckUserFunctionResponse> ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap.CheckUserFunctionAsync(ColleageInnerTraining.Web.AuthServiceProxy.CheckUserFunctionRequest request) {
            return base.Channel.CheckUserFunctionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.CheckUserFunctionResponse> CheckUserFunctionAsync(string applicationID, string authKey, string loginName) {
            ColleageInnerTraining.Web.AuthServiceProxy.CheckUserFunctionRequest inValue = new ColleageInnerTraining.Web.AuthServiceProxy.CheckUserFunctionRequest();
            inValue.Body = new ColleageInnerTraining.Web.AuthServiceProxy.CheckUserFunctionRequestBody();
            inValue.Body.applicationID = applicationID;
            inValue.Body.authKey = authKey;
            inValue.Body.loginName = loginName;
            return ((ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap)(this)).CheckUserFunctionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByApplicationIDResponse ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap.GetSystemUserByApplicationID(ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByApplicationIDRequest request) {
            return base.Channel.GetSystemUserByApplicationID(request);
        }
        
        public ColleageInnerTraining.Web.AuthServiceProxy.SystemUser[] GetSystemUserByApplicationID(string applicationID) {
            ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByApplicationIDRequest inValue = new ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByApplicationIDRequest();
            inValue.Body = new ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByApplicationIDRequestBody();
            inValue.Body.applicationID = applicationID;
            ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByApplicationIDResponse retVal = ((ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap)(this)).GetSystemUserByApplicationID(inValue);
            return retVal.Body.GetSystemUserByApplicationIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByApplicationIDResponse> ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap.GetSystemUserByApplicationIDAsync(ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByApplicationIDRequest request) {
            return base.Channel.GetSystemUserByApplicationIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByApplicationIDResponse> GetSystemUserByApplicationIDAsync(string applicationID) {
            ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByApplicationIDRequest inValue = new ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByApplicationIDRequest();
            inValue.Body = new ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByApplicationIDRequestBody();
            inValue.Body.applicationID = applicationID;
            return ((ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap)(this)).GetSystemUserByApplicationIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserBySysNoResponse ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap.GetSystemUserBySysNo(ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserBySysNoRequest request) {
            return base.Channel.GetSystemUserBySysNo(request);
        }
        
        public ColleageInnerTraining.Web.AuthServiceProxy.SystemUser GetSystemUserBySysNo(int sysNo) {
            ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserBySysNoRequest inValue = new ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserBySysNoRequest();
            inValue.Body = new ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserBySysNoRequestBody();
            inValue.Body.sysNo = sysNo;
            ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserBySysNoResponse retVal = ((ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap)(this)).GetSystemUserBySysNo(inValue);
            return retVal.Body.GetSystemUserBySysNoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserBySysNoResponse> ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap.GetSystemUserBySysNoAsync(ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserBySysNoRequest request) {
            return base.Channel.GetSystemUserBySysNoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserBySysNoResponse> GetSystemUserBySysNoAsync(int sysNo) {
            ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserBySysNoRequest inValue = new ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserBySysNoRequest();
            inValue.Body = new ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserBySysNoRequestBody();
            inValue.Body.sysNo = sysNo;
            return ((ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap)(this)).GetSystemUserBySysNoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByLoginNameResponse ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap.GetSystemUserByLoginName(ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByLoginNameRequest request) {
            return base.Channel.GetSystemUserByLoginName(request);
        }
        
        public ColleageInnerTraining.Web.AuthServiceProxy.SystemUser GetSystemUserByLoginName(string loginName) {
            ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByLoginNameRequest inValue = new ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByLoginNameRequest();
            inValue.Body = new ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByLoginNameRequestBody();
            inValue.Body.loginName = loginName;
            ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByLoginNameResponse retVal = ((ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap)(this)).GetSystemUserByLoginName(inValue);
            return retVal.Body.GetSystemUserByLoginNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByLoginNameResponse> ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap.GetSystemUserByLoginNameAsync(ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByLoginNameRequest request) {
            return base.Channel.GetSystemUserByLoginNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByLoginNameResponse> GetSystemUserByLoginNameAsync(string loginName) {
            ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByLoginNameRequest inValue = new ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByLoginNameRequest();
            inValue.Body = new ColleageInnerTraining.Web.AuthServiceProxy.GetSystemUserByLoginNameRequestBody();
            inValue.Body.loginName = loginName;
            return ((ColleageInnerTraining.Web.AuthServiceProxy.AuthServiceSoap)(this)).GetSystemUserByLoginNameAsync(inValue);
        }
    }
}
